#! /bin/bash

sudo docker stop grafana-influxdb
sudo docker rm grafana-influxdb
sudo docker pull anduin/grafana-influxdb

sudo docker run -d -v /etc/localtime:/etc/localtime:ro -p 80:80 -p 8083:8083 -p 8084:8084 -p 8086:8086 --name grafana-influxdb anduin/grafana-influxdb
