#! /bin/bash

sudo docker stop nginx_proxy
sudo docker rm nginx_proxy
sudo docker pull anduin/nginx_proxy

sudo docker run -d -p 8090:8090 --link es_kibana:es_kibana --name nginx_proxy anduin/nginx_proxy
