#!/usr/bin/env bash

if [ -z "$COUCHDB_DIR" ]; then
    export COUCHDB_DIR=/data/couchdb
fi

if [ -z "$COUCHDB_USER" ]; then
    export COUCHDB_USER=admin
fi

if [ -z "$COUCHDB_PASSWORD" ]; then
    export COUCHDB_PASSWORD=admin
fi

mkdir -p $COUCHDB_DIR/data $COUCHDB_DIR/logs

envsubst < /usr/local/etc/couchdb/local.ini.tmpl > /usr/local/etc/couchdb/local.ini

chmod 664 /usr/local/etc/couchdb/*.ini
chmod 775 /usr/local/etc/couchdb/*.d

# Run everything
/usr/bin/supervisord --configuration /etc/supervisor/supervisord.conf
